### ISSUE TITLE
Template doesn't fully work for Clockify Pro

### ISSUE THREAD

**Issue by lucasvillamor** [OscarValerock/Clockify-PowerBI#10]
Greetings, 

The template worked wonderfully while we stayed on clockify free. However, we've recently upgraded to Pro Plan, and the new modules like expenses or time-off, won't show up in Power BI. 

I'll be grateful if anyone knows any kind of solution.

**Comment by OscarValerock** [comment]
These are non-developed endpoints, and the template focuses on the free Clockify features. These are outside my pipeline for development as they are not broadly required; if you require the development of these endpoints, please contact me directly, and I can direct you to people that can develop such functionality.
