### ISSUE TITLE
Can't add https://reports.api.clockify.me/v1 to gateway

### ISSUE THREAD

**Issue by The-Power-BI-Guy** [OscarValerock/Clockify-PowerBI#12]
I ensured the connector is where the gateway can read it, but it is giving me this error:

Unable to create connection for the following reason: Unable to connect to the data source. Either the data source is inaccessible, a connection timeout occurred, or the data source credentials are invalid. Please verify the data source configuration and contact a data source administrator to troubleshoot this issue.

I am using the template, and we are not hosted on-site.

Really appreciate your support!

**Comment by The-Power-BI-Guy** [comment]
Just wanted to follow-up on this. I noticed it seems to derive from the Details report based on the parameters set up. All of the other tables will refresh, but I like how the details report pulls the information together and would like to continue to utilize the template as it's been set up.

**Comment by OscarValerock** [comment]
Which is the connection you are using, the *.PBIT file or the MEZ?

**Comment by OscarValerock** [comment]
For the PBIT file, you do not need a gateway. The only thing you require are the credentials.

**Comment by The-Power-BI-Guy** [comment]
Thank you, Oscar. I really appreciate the support. 

So how do you 'remove' the private level? I'd like to keep the information as it's been put together, but don't know how to approach that. I'll work on the credentials piece as well and get back to you.

**Comment by TinaCastillo09** [comment]
> Tried to adjust the credentials in the power bi service and this comes up ![image](https://user-images.githubusercontent.com/142523263/262116042-225e1b1b-e738-411b-8904-c9a7dc657578.png)

I have the same error. Did you figure out a way around this?

**Comment by OscarValerock** [comment]
Hi @vvazquezr @The-Power-BI-Guy  @TinaCastillo09 - Please refer to [this issue](https://github.com/OscarValerock/Clockify-PowerBI/issues/17) where I will follow up on the connection issues:
