### ISSUE TITLE
Gateway data source credentials cannot be added

### ISSUE THREAD

**Issue by Peteris-E** [OscarValerock/Clockify-PowerBI#14]
Hi, 
I am facing an issue where I cannot add gateway data source credentials. Getting error:
![image](https://github.com/OscarValerock/Clockify-PowerBI/assets/85337308/b46c8bf0-0f66-4486-8423-2bc65924e25b)

Details:
1. Using MEZ connector, data in PowerBI Desktop syncs successfully.
2. Added MEZ connector to on-prem PowerBI Gateway.
3. I can add PowerBI Gateway from the service, but cannot add the credentials, I am specifyig the same Clockify API key, which works for PowerBI Desktop.

Any suggestions?

**Comment by Peteris-E** [comment]
Actually, I was able to solve the issue with the help of these to article and a bit of community:
https://docs.microsoft.com/en-us/power-query/handlinggatewaysupport
https://docs.microsoft.com/en-us/power-query/samples/trippin/9-testconnection/readme

I added TestConnection line to the connector:
![image](https://github.com/OscarValerock/Clockify-PowerBI/assets/85337308/ed04ddd3-c269-401b-acea-d23c2cdcfeeb)

**Comment by OscarValerock** [comment]
Hey @Peteris-E , thanks a lot for the solution! I've modified the code in the project and the MEZ file.
