### ISSUE TITLE
OLE DB or ODBC Error

### ISSUE THREAD

**Issue by AlexP524** [OscarValerock/Clockify-PowerBI#16]
Hi Oscar.  A huge thank you for this tool!  Its a great help.  Unfortunately, I ran into an issue today.  I noticed that it was only pulling in 500 of our project records from Clockify.  We have over 2500.  So I changed the PageSize parameter to 5000 and now when I apply the changes I get the following:

`OLE DB or ODBC error: [DataSource.Error] Web.Contents failed to get contents from 'https://reports.api.clockify.me/v1/workspaces/61a64c350b6d292c343f4465/reports/detailed' (400): Bad Request.`

Any suggestions?  TIA.

**Comment by OscarValerock** [comment]
Hey Alex, are you using the MEZ connector or a query you wrote?

**Comment by OscarValerock** [comment]
Hi @AlexP524  Please refer to [this issue](https://github.com/OscarValerock/Clockify-PowerBI/issues/17) where I will follow up on the connection issues.
