### ISSUE TITLE
OLE DB or ODBC Error

### ISSUE THREAD

**Issue by qproff** [OscarValerock/Clockify-PowerBI#20]
Purchased the template and using v2.3.

All tables error during load, precipitated by the Tasks table returning:
`OLE DB or ODBC error: [DataSource.Error] The downloaded data is HTML, which isn't the expected type. The URL may be wrong or you might not have provided the right credentials to the server..`

Interesting Tasks preview loads fine in the query editor.

**Comment by qproff** [comment]
I was able to resolve this by removing a secondary workspace on my Clockify account. Note the v2.3 paid report has a default filter set to the 'PWC' workspace that needs to be cleared @OscarValerock

**Comment by OscarValerock** [comment]
Thanks for the notification @qproff , we have sent an update of the PBIT file.
