### ISSUE TITLE
Getting an error file uploading the data from clockify to power bi

### ISSUE THREAD

**Issue by Vinuvnath** [OscarValerock/Clockify-PowerBI#6]
Hi,
Iam using power bi and clokify connector for the past few months , and it was working properly .But from yesterday onwards its starts showing some error like below.

DataSource.Error: Web.Contents failed to get contents from 'https://api.clockify.me/api/v1/workspaces/5be008f2b0798754befe2030/projects/6218b9516a6eba63b0fe4df0/tasks?page-size=5000' (400): Bad Request
Details:
    DataSourceKind=Clockify
    DataSourcePath=Clockify
    Url=https://api.clockify.me/api/v1/workspaces/5be008f2b0798754befe2030/projects/6218b9516a6eba63b0fe4df0/tasks?page-size=5000

Can you please help

Thanks

**Comment by OscarValerock** [comment]
Hey @Vinuvnath, is this error related to the the *.pbit template file or the *.mez connector file?

**Comment by Vinuvnath** [comment]
.mez connector file

**Comment by Vinuvnath** [comment]
@OscarValerock Yes i worked on the recent update

**Comment by Vinuvnath** [comment]
![image](https://user-images.githubusercontent.com/78893904/177539734-13a14ec5-3fa3-4cd5-8684-02d41227b5a3.png)

**Comment by OscarValerock** [comment]
Closing issue as there was no further information.
