### ISSUE TITLE
Data doesn't load to the power BI editor 

### ISSUE THREAD

**Issue by tijsousa** [OscarValerock/Clockify-PowerBI#8]
Data is ok in the Power Query but it doesn't load do the power BI editor. These are the errors report:

Workspaces
O carregamento foi cancelado devido a um erro no carregamento de uma tabela anterior.
Users
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Clients
A coluna "Client ID" na Tabela "Clients" contém valores em branco, o que não é permitido em colunas do lado de uma relação de muitos para um ou em colunas que são utilizadas como a chave primária de uma tabela.
Projects
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Tasks
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Time Entries
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Time Entries Tags
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Tags
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
00 Measures
O carregamento foi cancelado devido a um erro no carregamento de uma tabela anterior.
Detailed Report
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.
Detailed Report Tags
Erro OLE DB ou ODBC: Excepção de HRESULT: 0x80040E4E.

**Comment by OscarValerock** [comment]
Is this issue related to the PBIT (template) or the *.MEZ (custom connector) file?
I believe the error is self explanatory, in your case the "Clients" table contains a blank client ID. Have you created any client on your Clockify instance?

**Comment by OscarValerock** [comment]
Closing issue for lack of follow-up
