### ISSUE TITLE
Automatic Refresh does not work

### ISSUE THREAD

**Issue by vikitsich** [OscarValerock/Clockify-PowerBI#9]
We use the custom connector to get data from the Clockify API. Everything works fine on PowerBI desktop, but when we turn on the automatic refresh on the PowerBI service the dataset fails to refresh. The error is the following:

Data source error: Column 'Project ID' in Table 'Projects' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
Cluster URI: WABI-NORTH-EUROPE-L-PRIMARY-redirect.analysis.windows.net
Activity ID: 5ab5cd08-66ba-46d0-822b-3b44b97a0a93
Request ID: 22beef8f-e799-493b-b9b1-d7d5564a79d5
Time: 2022-12-14 07:18:37Z

We have tried everything that could:
1. Re-installed the custom connector on the getaway
2. Updated the getaway
3. Removed all the blank and duplicate values from every table with PowerQuery
4. Removed the mentioned table, but then we got the same error message for another table. 

Also, some times when we upload the dataset with no relationships it refreshes the data, but it returns blank tables.

**Comment by OscarValerock** [comment]
Please confirm this is related to the MEZ file.

**Comment by vikitsich** [comment]
The problem was due to a bug in PowerBI service, all the datasets that had a gateway connection could not refresh. I did not have to do with the MEZ file.

**Comment by OscarValerock** [comment]
OK then, I will close this issue. Thanks.
